version: '3.3'

services:
  db:
    image: 'postgres:13'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=library_management
    ports:
      - '5432:5432'
     
  web:
    build: .
    command: python /LibraryManagement/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/LibraryManagement
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  
volumes:
  postgres_data:
