# Generated by Django 4.0.5 on 2022-09-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookmanageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('book', 'Book'), ('magazine', 'Magazine')], max_length=10)),
                ('account_number', models.PositiveBigIntegerField()),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
                ('bill_number', models.PositiveBigIntegerField()),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ISBN_number', models.PositiveBigIntegerField()),
                ('remarks', models.TextField()),
                ('softcopy', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'books_tbl',
            },
        ),
    ]
